In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("bangladesh food price index.csv")
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1261.4,27.0182
2,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1055.6,22.6101
3,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1288.75,27.362
4,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1060.0,22.5053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13549,2024-08-15,Sylhet,Maulvibazar,Maulavibazar Sadar,24.491369,91.763765,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,127.5,1.0814
13550,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,cereals and tubers,Rice (coarse),KG,aggregate,Retail,BDT,49.0,0.4156
13551,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,oil and fats,Oil (palm),L,aggregate,Retail,BDT,136.0,1.1535
13552,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,122.5,1.039
13553,2024-08-15,Sylhet,Sylhet,Sylhet Sadar,24.890531,91.871936,cereals and tubers,Wheat flour,KG,aggregate,Retail,BDT,60.0,0.5089

In [2]:

# Remove metadata row (first row contains column descriptions)
df = df[df["date"] != "#date"].copy()
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1261.4,27.0182
2,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1055.6,22.6101
3,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1288.75,27.362
4,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1060.0,22.5053
5,1998-09-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1415.5,30.0531
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13549,2024-08-15,Sylhet,Maulvibazar,Maulavibazar Sadar,24.491369,91.763765,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,127.5,1.0814
13550,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,cereals and tubers,Rice (coarse),KG,aggregate,Retail,BDT,49.0,0.4156
13551,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,oil and fats,Oil (palm),L,aggregate,Retail,BDT,136.0,1.1535
13552,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,122.5,1.039
13553,2024-08-15,Sylhet,Sylhet,Sylhet Sadar,24.890531,91.871936,cereals and tubers,Wheat flour,KG,aggregate,Retail,BDT,60.0,0.5089

In [4]:

# Convert date column to datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [5]:

# Filter only 2024 data
df_2024 = df[df["date"].dt.year == 2024].copy()

# Select and rename required columns
expected_format = df_2024[["commodity", "unit", "price", "currency"]].copy()
expected_format.columns = ["item", "unit", "price", "currency"]

# Optional: reset index
expected_format.reset_index(drop=True, inplace=True)

# Save to new CSV (optional)
expected_format.to_csv("bangladesh_food_prices_2024_formatted.csv", index=False)

print(expected_format.head())

                        item     unit   price currency
0  Potatoes (Holland, white)       KG    52.5      BDT
1                Wheat flour       KG    51.0      BDT
2               Eggs (brown)  1 piece    13.0      BDT
3                      Sugar       KG   130.0      BDT
4                 Oil (palm)        L  142.25      BDT

In [6]:
new_df = pd.read_csv("bangladesh_food_prices_2024_formatted.csv")
new_df

                           item     unit   price currency
0     Potatoes (Holland, white)       KG   52.50      BDT
1                   Wheat flour       KG   51.00      BDT
2                  Eggs (brown)  1 piece   13.00      BDT
3                         Sugar       KG  130.00      BDT
4                    Oil (palm)        L  142.25      BDT
...                         ...      ...     ...      ...
4160            Lentils (masur)       KG  127.50      BDT
4161              Rice (coarse)       KG   49.00      BDT
4162                 Oil (palm)        L  136.00      BDT
4163            Lentils (masur)       KG  122.50      BDT
4164                Wheat flour       KG   60.00      BDT

[4165 rows x 4 columns]